apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: microservices-webapp
  labels:
    app: microservices-webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: microservices-webapp
